BPM Status message
ONSdigital/es-ingest-takeon-data pull request #65
Opened 2020-10-01 12:20 UTC by glanvl

Saul did most of the implementation of the status message in ingest. We decided if they were running bricks they would see a ingest message from both ingest wrangler and bricks wrangler but didn't feel this was an issue. Other work will be done around exactly what the users see.
 - Status message in both wranglers
 - Error message in wranglers and methods

2020-10-08 13:42 UTC, phunter33 submitted a review, later dismissed
Improved runtime vars for error messages.

2020-10-08 13:43 UTC, Piwington requested changes

2020-10-08 13:43 UTC, Piwington commented on ingest_brick_type_method.py
> +    bpm_queue_url = None
This seems unneeded to me. It should never fail to be assigned as Marshmallow will complain if this variable isn't passed in. This is why no other variables other than run_id are preset like this.

2020-10-08 13:43 UTC, Piwington commented on ingest_brick_type_wrangler.py
> +    current_step_num = "1"
What is this variable for? It just looks like it is being passed through directly?

Would prefer if this variable was set alongside all the other lower down to keep them together.
As for URL same as above.

2020-10-08 13:43 UTC, Piwington commented on ingest_takeon_data_method.py
> +    bpm_queue_url = None
Same as above.

2020-10-08 13:43 UTC, Piwington commented on ingest_takeon_data_wrangler.py
> +    current_step_num = "1"
As above

2020-10-08 13:57 UTC, glanvl commented on ingest_brick_type_method.py
> +    bpm_queue_url = None
Fair play.

2020-10-08 14:07 UTC, Piwington approved these changes

2020-10-08 14:13 UTC, Piwington approved these changes
Happy for now. Mentioned separately about current_step_num variable to Luke. As seems like we are reintroducing Checkpoint Numbers we deliberately removed. Seems to be there just to get this temporary queue message running so won't have a big debate over it at this time.

2020-10-12 09:34 UTC, kingmushroom approved these changes

2020-10-13 09:03 UTC, merged